[application]
name = "LanGameScan"
tailwind_input = "input.css"

[web.app]
title = "LAN Game Scan"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.madone.lan_game_scan"
publisher = "Mad_One"
icon = ["assets/icon.png"]
category = "Network"
short_description = "LAN Game Server Browser"
long_description = "Discover and browse game servers on your local network."